### PR TITLE
Auto Attack Toggle

### PR DESCRIPTION
**Pull request by AetherV**
May potentially need a new sound file, but I have no clue where to find them.

### CODE REVIEW

**Comment by AetherV** [comment]
#154

**Comment by dodekeract** [comment]
@AetherV not a complete list, but [these](https://github.com/dodekeract/manta-config-engine/blob/master/data/sounds.json) are some of the important ones.

**Comment by AetherV** [comment]
Ah nice, I will play around with those. Where do you find the sound files, are they packaged into a VPK or something? Currently can't find anything in my `C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\sounds\ui` Folder

**Comment by dodekeract** [comment]
@AetherV I haven't done that myself. Here is [the conversation](https://github.com/dodekeract/manta-config-engine-app/issues/49#issuecomment-202131764) on the issue that addressed this in Manta.

**Comment by AetherV** [comment]
Interesting, sounds like it's hidden in one of the vpks -.-'. I'll take a look through the tools if I find a few extras that might suit my needs but I think for now I'll stick with the list you gave.

**Comment by loopuleasa** [comment]
Thanks for the contribution.

**Pull request merged**
