### PR TITLE
Reborn: F7 toggle Quick Attack + Markdown on README

### PR DESCRIPTION
**Pull request by SkipKayhil**

### CODE REVIEW

**Comment by SkipKayhil** [comment]
Sorry, I thought you were wanting it toggleable with F7 like the legacy version.

**Comment by loopuleasa** [comment]
Afaik legacy has always on quick attack/follow, unless I merged something.

Basically, always quick attack. Like people want it.

**Comment by SkipKayhil** [comment]
>for legacy, make quick attack/follow be affected by the F7 quick/normal mode toggle
was in issue #26, then I added that to legacy, then you said also add that to Reborn. Just trying to help :+1:

**Comment by loopuleasa** [comment]
Sorry about that, there's a mess in my head.
But yeah, I didn't think it through. Quick attack is way better than A+Click, so I just keep it default, because I am not sure I want that tied to the F7.

**Pull request closed without merging**
