### PR TITLE
Closes issue #93, deletes legacy folder.

### PR DESCRIPTION
**Pull request by don4of4**
Legacy configs will forever be available in the git repo history.  In the (unlikely) event anyone ever wants them, they will be available.

### CODE REVIEW

**Comment by dodekeract** [comment]
The `Dota 2 Reborn Keyboard Setups` should get a new name too then.

**Comment by loopuleasa** [comment]
that name seems fine to me

but feel free to suggest alternatives

**Comment by don4of4** [comment]
I think he's trying to say the naming is redundant...  I tend to agree, but I would also like to see the rest of the folders renamed to be more streamlined.  I.e. "!! THE CORE..."

**Comment by dodekeract** [comment]
Yes, I'm implying the name is redundant. There is nothing else than Reborn anymore. It's should be just called Dota 2. Newer players won't even know what the fuck Reborn is.

**Pull request merged**
