### PR TITLE
new upd8 dota

### PR DESCRIPTION
**Pull request by githubron726**
upd8

### CODE REVIEW

**Comment by loopuleasa** [comment]
there are too many changes for me to merge this one

**Comment by don4of4** [comment]
What is this functionality wise?  

Also, this pull request would be disastrous to merge.  When you have a pull with these many changes, you should be rebasing your branch to incorporate new changes instead of merging.  At this point you should either use a diff of your code to master to create a .patch (and a new pull) or you should squash the commits with an interactive rebase.

Let me know if you need help.

**Comment by loopuleasa** [comment]
No, this one is not relevant, this is a different branch that the OP worked on.

**Comment by Sembrani** [comment]
Since this is not going to be merged, can you close it without merging please? Just cleans up the Merge requests area.

**Pull request closed without merging**
