### PR TITLE
Temp fix for Mouse3

### PR DESCRIPTION
**Pull request by AetherV**
I hope I am doing this right. I tried to add a temporary solution to the Middle Mouse problem by adding a line of text to the dota2_keybinds_default.cfg file. This should make the Mouse3 button work again.

### CODE REVIEW

**Comment by kingalca** [comment]
Fix is non-functional after player makes usage oft SPACE + H (show score). Cameragrip doesn't work afterwards. Also, tabbing out of the game renders it useless.

**Comment by loopuleasa** [comment]
Good spot, I'll need to look into it more.

**Comment by AetherV** [comment]
@kingalca Okay that is strange, it seems to work by me...Can you give me a screenshot of the console after the bug takes place? A possible cause for this to be, is if `
execing dota2_gameplay_mode/dota2_keybinds_default.cfg
` is not executed after the space or alt modifier

**Comment by kingalca** [comment]
Will check it. Im using Linux, maybe this is a reason? But I can't imagine one. 

Seems like that there are several combinations to render mouse3-bindings useless. Pretty annyoing but once you type it in the console its quick fixed if its broken again.

**Comment by AetherV** [comment]
Hmmm strange. Does the latest update to the configuration fix that (loop's)

**Comment by loopuleasa** [comment]
Mouse3 drag now works

**Comment by kingalca** [comment]
] bind mouse3 +cameragrip
execing dota2_gameplay_mode/dota2_keybinds_space_pressed.cfg
Telling Steam not to update the app for the next 900 seconds
Unknown command: echo
Unknown command: current_hero_space
execing dota2_gameplay_mode/dota2_keybinds_default.cfg
Unknown command: echo
Unknown command: current_hero

**Comment by AetherV** [comment]
It can't be line 1 as there is an unbind me. Secondly this patch was for the core file, not loops files. Try just dl the update loop pushed

**Comment by loopuleasa** [comment]
I can confirm there is an issue with Space and cameragrip getting stuck

I will investigate and see for a fix

**Comment by kingalca** [comment]
Also, ALT will trigger a reset.

**Comment by AetherV** [comment]
Huh. Cannot confirm this on my end. Guess I got some more testing to do. The whole reason I closed this pull is because the update was to the core config when it should have been to loops. That was my bad and I hoped that closing this would sort of delete this pull request (new to github, sorry). 

Just to be absolutely sure (I know this sounds stupid and all but I made a mistake with this pull), you are trying to use loops config and not the core config right? This fix was stupidly only applied to the core which cannot be applied to the rest of the configs. 

Side Note: I am right to assume that the Linux console functions the same as the windows one right?

**Comment by dodekeract** [comment]
Triple check your autoexec folder location. Maybe you updated the wrong folder of the 2.

**Comment by loopuleasa** [comment]
@kingalca 
I will have a look, or alternatively you can make a pull request.
Thanks for the help.

**Comment by kingalca** [comment]
I put the configs in the game/-Folder, which contains reborn. 

The last update only modified one file, I replaced it. However, I will delete all configs and re-install them and check again as well.

**Comment by AetherV** [comment]
Wait did you take the file from this pull request? Because if you did that, it won't be compatible with loop's config.

 In any case, once we solve this problem, can you delete this pull request @loopuleasa, seems to be causing a bit of confusing assuming I myself messed up.

**Comment by kingalca** [comment]
I... used thje config of loopuleasa. I see where I did a mistake. Sorry for the confuse. 

However, the problem exists in the current build of the layout of loopuleasa.

**Comment by AetherV** [comment]
Do you get the same console errors? Specifically the unknown command ______ bits

**Comment by kingalca** [comment]
Yes to both.

**Comment by AetherV** [comment]
Try downloading and using loops English config only and using check keyboard position.

 Problem is that we haven't patched the German keyboard layout yet, hope to do so when I get back home.

**Comment by kingalca** [comment]
Will check when I come home, but currently I am using only the english config and the exact same problem exists on my end.

**Comment by loopuleasa** [comment]
German layout wasn't updated yet.

The main layout has the problem with pressing ALT/SPACE while dragging the camera that I need to fix. It caused one or two deaths for me.

**Pull request closed without merging**
