### PR TITLE
Sad but true.

### PR DESCRIPTION
**Pull request by dodekeract**
- add warning for users finding this project
- add notice for valve

### CODE REVIEW

**Comment by AetherV** [comment]
Possible improvement would be adding links to the other projects that are being developed. Give them a bit of traffic, maybe a couple of devs would be willing to help build those projects up too. 

Ofc add the standard disclaimer that Valve may not take too kindly of their approaches either. Alternatives that should be mentioned should be:

- Project Arcana (http://steamcommunity.com/sharedfiles/filedetails/?id=408986743)
- Karrandalf's Oracle Autohotkey based solution (https://github.com/Karrandalf/Dota2-TheCore-Config-Engine)

**Comment by dodekeract** [comment]
@AetherV like this?

**Comment by AetherV** [comment]
Yep I'm happy :+1: 
Now just need to wait for @loopuleasa to approve this I guess

**Comment by AveYo** [comment]
I've removed my VAC warning on the release page because the mod is acknowledged as harmless and no action will be taken on it's users - worst case scenario - dotakeys will simply receive the autoexec.cfg treatment.
The news is that the hotkeys interface will receive an official facelift, but might not make it to the New Journey update. Until then, feel safe to use it.
If I get to make a III-rd release, it will probably feature a TheCore profile (as close to it as I can make it).

> **Important notice to Valve:** most definitely rhetorical
>  Instead of killing legit scripts that bring mostly ergonomic features, why not hunt down actual, reactive cheats from the Ensage family instead - it's been years! Just follow the money...
>  You've killed autoexec.cfg months ago, and still haven't delivered on GUI alternatives for many features that users have developed and got used to over the years.
>  But why do that in the first place?! How hard is to parse a +/- alias and just block multiple distinct abilities+items? Armlet toggling? it should have been nerfed years ago on the backend.
>
> **Important notice to Modders:** while this is not strictly VAC-safe,
>  it should be as long as there are no multiple {**distinct**} abilities/items per {**single**} hotkey.
>  Auto-Invoke, blink-call/duel, and any other ability and/or item combo scripts will always be illegal!
>  Please refrain from adding any of that!
>  D-OPTIMIZER does not condone cheating in any way so don't even ask about it!

**Comment by dodekeract** [comment]
@loopuleasa bump

**Comment by loopuleasa** [comment]
Sorry for being inactive.

**Pull request merged**
