### PR TITLE
Project Oracle

### PR DESCRIPTION
**Pull request by Karrandalf**
Contains no AHK.
For "Advanced" and "Basic" users.

The README.md under "Dota2-TheCore-Config-Engine" still needs to be updated.

### CODE REVIEW

**Comment by dodekeract** [comment]
FYI broken autoexec has nothing to do with Vulkan, at all.

**Comment by Karrandalf** [comment]
@dodekeract , The only relation they have is that they both occurred during the same update. Do you have a better name? I am open to suggestions.

**Comment by dodekeract** [comment]
They didn't even occur during the same update.

**Comment by Karrandalf** [comment]
@dodekeract, I apologize. They were one update apart.
Vulkan API on May 23rd, and the very next update on May 24th broke the autoexec.
I will still call it a "Dota 2 Vulkan Keyboard Setup" as the community here refers to the broken autoexec update as the "Vulkan Update" https://github.com/loopuleasa/Dota2-TheCore-Config-Engine/issues/160. Would you like to suggest an alternative name?

**Pull request closed without merging**
