### PR TITLE
Per Key ability and item quickcast toggles and Neatened files

### PR DESCRIPTION
**Pull request by Sembrani**
As per Issue #52, #26;

Using Alt+Space, and an ability / item key, that ability / item is toggled from quick-cast to normal-cast and back individually. "F7" will force all abilities and items to either quick-cast or normal-cast
depending on how many times it is pressed.

Excuse the potentially excessive binds in the additional file. I was having a problem with it and wanted to neaten the long scripts to be a little bit more readable. It works as-is, and I'm happier to leave it, though if someone wants to shorten it, go ahead.

NOTE: When Alt+Space is pressed, both keys have to be released before
either Alt or Space can be used as modifiers again.

### CODE REVIEW

**Comment by SkipKayhil** [comment]
I think excessive aliases aren't a bad thing, especially when its pretty backend like this. I think it helps readability for sure

**Comment by Sembrani** [comment]
Yeah, I'm going through and improving the read ability of all the config files at the moment. I'll have a pull request for that once this has gone through.

**Comment by Sembrani** [comment]
Wait, it's sneaking through anyway. Github behavior confuses me sometimes.

**Comment by Sembrani** [comment]
Working on moving the per key ability and item quickcast toggles to Legacy now

**Comment by Sembrani** [comment]
LEGACY BINDS CURRENTLY BROKEN. Will re-create pull request once fixed

**Comment by Sembrani** [comment]
Legacy binds had errors creep in. Copied changes from GitHub had a + at the start of the lines, which had to be removed. A smaller error than I originally thought.

**Comment by loopuleasa** [comment]
This is a big change and I'll have to review it first and see how it works.

Readability is very important, and there are bugs that can arise with a modifier key like ALT+SPACE that we have to be careful.

**Comment by Sembrani** [comment]
The merge conflict will likely be with the quick courier upgrade script that was pulled between me updating my fork and finishing this pull request.

**Comment by Sembrani** [comment]
No worries. If you have any problems understanding it, or any bugs/glitches that you find, let me know and I'll do my best to clarify / fix it.

**Comment by loopuleasa** [comment]
I have to confess I don't know how to solve merge conflicts in git using the command line

**Comment by Sembrani** [comment]
I think you might be able to undo the pull request #54 by @Mirarara, and I can quickly make that change that in my branch before you merge, or maybe @Mirarana will put a pull request in again... Might be hard to fix the conflict, because I changed so much.

**Comment by Mirarara** [comment]
I think undoing my pull request is much easier, and while you are at it, you can just fix the courier bug.

**Comment by Sembrani** [comment]
Ok, will commit those changes now.

**Comment by Sembrani** [comment]
Ok, looks like it can be merged automatically now @loopuleasa

**Comment by Sembrani** [comment]
Are there any issues with this being merged, or are you still testing this before merging? @loopuleasa

**Comment by loopuleasa** [comment]
Need to find some room to test, but I'll do it later

believe you did a good job

**Pull request merged**
