### PR TITLE
Implemented Hero Selection Script

### PR DESCRIPTION
**Pull request by Sembrani**
Changed some other binds, See merged commits.

Referencing #87

### CODE REVIEW

**Comment by loopuleasa** [comment]
Testing it right now.
Will handle the visual layouts later on today.

Exciting stuff!

**Comment by loopuleasa** [comment]
Space+F2 to jump to courier is not working.

The rest is working.
The select hero mode script is AMAZING!

**Comment by loopuleasa** [comment]
Alt+Selfcast doesnt seem to work.
I enabled a mode.

**Comment by Sembrani** [comment]
If ALT+Selfcast isn't working, then it's probably an issue with this line:
`alias "self_ability_0" "dota_ability_execute 0; dota_ability_execute 0"` 

Unless the ALT file isn't loading correctly.

**Pull request merged**
