### PR TITLE
Some Fixes v2

### PR DESCRIPTION
**Pull request by AetherV**
Removed the previous Pull, since I added an attempted fix for the auto attack script. It does not fully function like the original one, but I hope its a good base.

### CODE REVIEW

**Comment by AetherV** [comment]
@loopuleasa I'm gonna leave messages here so I don't spam everyone's emails (RIP Inbox yesterday).

The autoattack command got changed. I used modes 0 and 2 for the fix, You may want to change those depending on what you want the config to achieve (0, 1, 2 follows the settings order I think). Secondly, the auto attack has some strange interactions and needs a stop command in there, but dota_stop isn't working how I want it to. Maybe you can fix that.

**Comment by loopuleasa** [comment]
I can look into the dota_stop command

I have a question: What are with the .png file changes? They don't load correctly on my side.

**Comment by AetherV** [comment]
I don't know, they kept on preventing me from submitting a pull. They shouldn't be changed except they are for some reason. I suspect its my virus scanner being a whinny bit** as usual (need a better one anyways). If you can "uncommit" those or something that be fantastic.

**Comment by AetherV** [comment]
Oh and the PNG's don't load on my side either.

**Comment by loopuleasa** [comment]
What did you change on the pics?

I can try to do the changes manually on my side then merge them.

**Comment by AetherV** [comment]
No they shouldn't have. For some reason my PC hates PNG files and corrupts them... 
Just tried downloading the original config and they are also bugging out on me, which is really weird.

In any case, all my changes are:
Add the following to dota2_keybinds_default.cfg at the end of the file:

//Mouse3 Fix
bind mouse3 +cameragrip


Autoattack script (dota2_functions_active.cfg):
//  Auto attack toggle (must be first configured here to work properly)
alias "auto_attack_toggle" "auto_attack_toggle_on"
alias "auto_attack_toggle_on" "playsound sounds/ui/tutorial_ui_ding_01.vsnd_c;dota_player_units_auto_attack_mode 2;  alias auto_attack_toggle auto_attack_toggle_off; say_student Auto attack enabled"
alias "auto_attack_toggle_off" "playsound sounds/ui/ui_upgrade_ability_01.vsnd_c;dota_player_units_auto_attack_mode 0; alias auto_attack_toggle auto_attack_toggle_on; say_student Auto attack disabled"

**Comment by loopuleasa** [comment]
k, I will handle these

**Pull request closed without merging**
